{% set name = "dask-expr" %}
{% set version = "1.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dask_expr-{{ version }}.tar.gz
  sha256: 751409a304e697fbd920e3035bdc9af2111194dff5e699bfb25a193286f1e606

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - versioneer =0.28
    - tomli
  run:
    - python >=3.9
    - dask-core ==2024.6.0
    - pyarrow
    - pandas >=2

test:
  imports:
    - dask_expr
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dask/dask-expr
  summary: 'High Level Expressions for Dask'
  description: |
    High Level Expressions for Dask
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://github.com/dask/dask-expr/blob/main/README.md
  dev_url: https://github.com/dask/dask-expr

extra:
  recipe-maintainers:
    - fjetter
    - phofl
    - jrbourbeau
