{% set name = "dask-expr" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cbe1feacc99b6613c32551f8663f0adf4582a2446762e34c7d988a71d2c22e23

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - versioneer =0.28
    - tomli
  run:
    - python >=3.9
    - dask ==2024.2.1
    - pyarrow
    - pandas >=2

test:
  imports:
    - dask_expr
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dask-contrib/dask-expr
  summary: 'High Level Expressions for Dask'
  description: |
    High Level Expressions for Dask
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://github.com/dask-contrib/dask-expr/blob/main/README.md
  dev_url: https://github.com/dask-contrib/dask-expr

extra:
  recipe-maintainers:
    - phofl
    - jrbourbeau
